### ISSUE TITLE
页面错误

### ISSUE THREAD

**Issue by sunyong8860** [dotnet/AspNetCore.Docs.zh-cn#342] opened 2020-12-21 08:29 UTC
[Enter feedback here] The
original page:
is an API, it supports user interface**)** login function**( UI.
Should it be changed to:
is an API, it supports user interface (**login function**) ) **UI.
For a little obsessive-compulsive disorder, it looks a bit uncomfortable

[在此处输入反馈]
原来页面：
是一个 API，它支持用户界面**)** 登录功能 **(**UI。
是否应该改为：
是一个 API，它支持用户界面**(**登录功能 **)**UI。
对于有点强迫症来说，看着有点难受
---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 94bfd895-d2af-390b-0801-428b36a27ff4
* Version Independent ID: 0e0d870e-e49a-e16c-c259-68d58e701b8f
* English Content: [ASP.NET Core 简介 Identity](https://docs.microsoft.com/aspnet/core/security/authentication/identity?view=aspnetcore-3.1&tabs=visual-studio)
* Content: [ASP.NET Core 简介 Identity](https://docs.microsoft.com/zh-cn/aspnet/core/security/authentication/identity?view=aspnetcore-3.1&tabs=visual-studio)
* Content Source: [aspnetcore/security/authentication/identity.md](https://github.com/dotnet/AspNetCore.Docs.zh-cn/blob/live/aspnetcore/security/authentication/identity.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-security**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment] 2021-02-16 18:42
@JasonCard  translation problem

**Comment by Rick-Anderson** [comment] 2021-02-16 18:46
@JasonCard  should I change (UI) to \`(UI)\` ?
Or should we add `UI` to loc meta-data? It looks like the `(` and `)` are mistranslated in many places. That seems like a MT bug.

**Comment by JasonCard** [comment] 2021-02-16 19:15
@sunyong8860 @Rick-Anderson Thank you for reporting this issue. It does appear to be a MT engine issue, so I'll escalate this accordingly. Since the term UI is not over-localized, there's no need to add code style or no-loc metadata in source for this example. It appears to be a minor MT issue that's not blocking users, we won't manually address each instance of this issue, but we hope the root cause will be addressed in the MT engine. Fix to MT engine can take a long time, so I'll close this issue for now.

**Closed by JasonCard** 2021-02-16 19:15 UTC
